/* 

I am trying to write a js script for a rock paper scissors game.
The game is set in the console and is human vs computer.
this means i need a way to get both the human input and computer input.
the computer choice can be randomly generated by math.random() and using it to pick a string from an array
for the human input i need to find a way to ask for an input from the user in the console
I can actually just link it to an empty html page and use promt() and alert() functions to play the game
I can use a function to compare the user and computer choices and determine the outcome of the game
use conditional statements to check

I know the computer will be using numbers as input ex. 1 = rock, 2 = paper, 3 = scissors
I'll expalin in the prompt how to make a selection
then i can just do a comparison and return a winner based on that


*/

let getComputerChoice = function () {
    let random = Math.floor(Math.random() * 3);
    const rps = ["rock", 'paper', 'scissors'];
    return rps[random];
}

let playerChoice = prompt("Choose rock, paper, or scissors");
let computerChoice = getComputerChoice();


const rps = function (computerChoice = getComputerChoice(), playerChoice = playerChoice) {
    console.log(playerChoice);
        if (playerChoice == computerChoice) {
            return 'Its a tie';
        } else if (playerChoice == 'rock') {
            if (computerChoice == 'paper') {
                computerWins++;
                return 'You lose. paper beats rock';
            } else {
                playerWins++;
                return 'you win. rock beats scissors';
            }
        } else if (playerChoice === 'paper') {
            if (computerChoice === "scissors") {
                computerWins++;
                return 'you lose. scissors beats paper';
            } else {
                playerWins++;
                return 'you win. paper beats rock';
            }
        } else if (playerChoice === 'scissors') {
            if (computerChoice === 'rock') {
                computerWins++;
                return 'you lose. rock beats scissors';
            } else {
                playerWins++;
                return 'you win. scissors beats paper';
            }
        }else {
            return 'Invalid input please try again';
        }


}

// a function to play five rounds of rock paper scissors based on looping over the rps funcion
function playRound() {
    for (let round = 1; round <= 5; round++) {
        let playerChoice = prompt("Choose rock, paper, or scissors").toLowerCase;
        let computerChoice = getComputerChoice();
        console.log(playerChoice);
        console.log(computerChoice);
        let computerWins = 0;
        let playerWins = 0;
        let outcome = rps();
        console.log(outcome);
        console.log(`Score = Computer: ${computerWins}, Player: ${playerWins}`);
    }
}

//playRound();
 rps();
 console.log(rps());
